In [1]:
import pandas as pd 
import nltk
import re
import string

In [2]:
df = pd.read_csv(r'C:\Users\admin\Documents\Roshan\mlops1\data\raw\train.csv',sep=';',header=None)

In [3]:
df.head()

                                                   0        1
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df = df.rename(columns={0:'text',1:'sentiment'})
df

                                                    text sentiment
0                                i didnt feel humiliated   sadness
1      i can go from feeling so hopeless to so damned...   sadness
2       im grabbing a minute to post i feel greedy wrong     anger
3      i am ever feeling nostalgic about the fireplac...      love
4                                   i am feeling grouchy     anger
...                                                  ...       ...
17995  i just keep feeling like someone is being unki...     anger
17996  im feeling a little cranky negative after this...     anger
17997  i feel that i am useful to my people and that ...       joy
17998  im feeling more comfortable with derby i feel ...       joy
17999  i feel all weird when i have to meet w people ...      fear

[18000 rows x 2 columns]

In [5]:
df.head()

                                                text sentiment
0                            i didnt feel humiliated   sadness
1  i can go from feeling so hopeless to so damned...   sadness
2   im grabbing a minute to post i feel greedy wrong     anger
3  i am ever feeling nostalgic about the fireplac...      love
4                               i am feeling grouchy     anger

In [6]:
df['sentiment'].value_counts()

sentiment
joy         6057
sadness     5247
anger       2434
fear        2161
love        1463
surprise     638
Name: count, dtype: int64

In [7]:
df.isnull().sum()

text         0
sentiment    0
dtype: int64

In [8]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [9]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [10]:

lemma = WordNetLemmatizer()


df['cleaned'] = df['text'].str.replace('[^a-zA-Z]', ' ', regex=True).str.lower()

df['cleaned'] = df['cleaned'].str.split()

df['lemma'] = df['cleaned'].apply(lambda words: ' '.join([lemma.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]))

df.drop('cleaned', axis=1, inplace=True)

In [11]:
df.head()

,text,sentiment,lemma
0,i didnt feel humiliated,sadness,didnt feel humiliated
1,i can go from feeling so hopeless to so damned...,sadness,go feeling hopeless damned hopeful around some...
2,im grabbing a minute to post i feel greedy wrong,anger,im grabbing minute post feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...,love,ever feeling nostalgic fireplace know still pr...
4,i am feeling grouchy,anger,feeling grouchy

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [13]:
tfidf = TfidfVectorizer(max_features=500, stop_words='english')
x = tfidf.fit_transform(df['lemma']).toarray()

In [14]:
df.head()

,text,sentiment,lemma
0,i didnt feel humiliated,sadness,didnt feel humiliated
1,i can go from feeling so hopeless to so damned...,sadness,go feeling hopeless damned hopeful around some...
2,im grabbing a minute to post i feel greedy wrong,anger,im grabbing minute post feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...,love,ever feeling nostalgic fireplace know still pr...
4,i am feeling grouchy,anger,feeling grouchy

In [15]:
x.shape

(18000, 500)

In [16]:
xx = pd.DataFrame(x)
xx['sentiment'] = df['sentiment']

In [17]:
xx

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,sentiment
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.489616,0.0,0.0,0.0,0.0,0.0,anger
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,love
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,anger
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.559320,0.0,0.0,0.0,0.0,0.0,anger
17996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,anger
17997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,joy
17998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,joy
17999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,fear

In [ ]:
#pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in c:\users\admin\documents\roshan\mlops1\venv\lib\site-packages (from imbalanced-learn->imblearn) (2.2.1)
Requirement already satisfied: scipy<2,>=1.10.1 in c:\users\admin\documents\roshan\mlops1\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.15.0)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in c:\users\admin\documents\roshan\mlops1\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.6.0)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn->imblearn)
  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: joblib<2,>=1.1.1 in c:\users\admin\documents\roshan\mlops1\venv\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\admin\documents\roshan\mlops1\venv\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.13.0 imblearn-0.0 sklearn-compat-0.1.3
Note: you may need to restart the kernel to use updated packages.

In [18]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [19]:
y = df['sentiment']
x,y = smote.fit_resample(xx.drop('sentiment',axis=1),y)

In [20]:
y.value_counts()

sentiment
sadness     6057
anger       6057
love        6057
surprise    6057
fear        6057
joy         6057
Name: count, dtype: int64

In [21]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB, ComplementNB, GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
model = SVC(random_state=42)

model.fit(x_train, y_train)

# Make Predictions
y_pred = model.predict(x_test)

# Evaluate Model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.848534874122988

Classification Report:
               precision    recall  f1-score   support

       anger       0.91      0.82      0.86      1241
        fear       0.82      0.82      0.82      1160
         joy       0.70      0.83      0.76      1191
        love       0.90      0.89      0.90      1234
     sadness       0.84      0.77      0.80      1235
    surprise       0.95      0.96      0.96      1208

    accuracy                           0.85      7269
   macro avg       0.85      0.85      0.85      7269
weighted avg       0.85      0.85      0.85      7269

In [23]:
y_pred[:10]

array(['surprise', 'surprise', 'fear', 'joy', 'anger', 'anger', 'fear',
       'fear', 'anger', 'sadness'], dtype=object)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB, ComplementNB, GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
model = RandomForestClassifier(random_state=42)

model.fit(x_train, y_train)

# Make Predictions
y_pred = model.predict(x_test)

# Evaluate Model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8382170862567065

Classification Report:
               precision    recall  f1-score   support

       anger       0.88      0.85      0.86      1241
        fear       0.84      0.83      0.83      1160
         joy       0.68      0.77      0.72      1191
        love       0.88      0.88      0.88      1234
     sadness       0.84      0.74      0.79      1235
    surprise       0.93      0.96      0.94      1208

    accuracy                           0.84      7269
   macro avg       0.84      0.84      0.84      7269
weighted avg       0.84      0.84      0.84      7269