In [1]:
import pandas as pd 
import nltk
import re
import string

In [2]:
df = pd.read_csv(r'C:\mlops1\data\raw\train.csv',sep=';',header=None)

In [3]:
df.head()

                                                   0        1
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df = df.rename(columns={0:'text',1:'sentiment'})
df

                                                    text sentiment
0                                i didnt feel humiliated   sadness
1      i can go from feeling so hopeless to so damned...   sadness
2       im grabbing a minute to post i feel greedy wrong     anger
3      i am ever feeling nostalgic about the fireplac...      love
4                                   i am feeling grouchy     anger
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...   sadness
15996  i am now turning and i feel pathetic that i am...   sadness
15997                     i feel strong and good overall       joy
15998  i feel like this was such a rude comment and i...     anger
15999  i know a lot but i feel so stupid because i ca...   sadness

[16000 rows x 2 columns]

In [5]:
df.head()

                                                text sentiment
0                            i didnt feel humiliated   sadness
1  i can go from feeling so hopeless to so damned...   sadness
2   im grabbing a minute to post i feel greedy wrong     anger
3  i am ever feeling nostalgic about the fireplac...      love
4                               i am feeling grouchy     anger

In [6]:
df['sentiment'].value_counts()

sentiment
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [7]:
df.isnull().sum()

text         0
sentiment    0
dtype: int64

In [8]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [9]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [10]:

lemma = WordNetLemmatizer()


df['cleaned'] = df['text'].str.replace('[^a-zA-Z]', ' ', regex=True).str.lower()

df['cleaned'] = df['cleaned'].str.split()

df['lemma'] = df['cleaned'].apply(lambda words: ' '.join([lemma.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]))

df.drop('cleaned', axis=1, inplace=True)

In [12]:
df.head()

,text,sentiment,lemma
0,i didnt feel humiliated,sadness,didnt feel humiliated
1,i can go from feeling so hopeless to so damned...,sadness,go feeling hopeless damned hopeful around some...
2,im grabbing a minute to post i feel greedy wrong,anger,im grabbing minute post feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...,love,ever feeling nostalgic fireplace know still pr...
4,i am feeling grouchy,anger,feeling grouchy

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [14]:
tfidf = TfidfVectorizer(max_features=500, stop_words='english')
x = tfidf.fit_transform(df['lemma']).toarray()

In [18]:
df.head()

,text,sentiment,lemma
0,i didnt feel humiliated,sadness,didnt feel humiliated
1,i can go from feeling so hopeless to so damned...,sadness,go feeling hopeless damned hopeful around some...
2,im grabbing a minute to post i feel greedy wrong,anger,im grabbing minute post feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...,love,ever feeling nostalgic fireplace know still pr...
4,i am feeling grouchy,anger,feeling grouchy

In [19]:
x.shape

(16000, 500)

In [23]:
xx = pd.DataFrame(x)
xx['sentiment'] = df['sentiment']

In [24]:
xx

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,sentiment
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.491894,0.0,0.0,0.0,0.0,0.0,anger
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,love
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,anger
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
15996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness
15997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,joy
15998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,anger
15999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,sadness

In [21]:
y = df['sentiment']

x_train, x_test, y_train, y_test = train_test_split(xx, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
model = RandomForestClassifier()

model.fit(x_train, y_train)

# Make Predictions
y_pred = model.predict(x_test)

# Evaluate Model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.734375

Classification Report:
               precision    recall  f1-score   support

       anger       0.79      0.64      0.71       427
        fear       0.75      0.67      0.71       397
         joy       0.66      0.87      0.75      1021
        love       0.75      0.54      0.63       296
     sadness       0.82      0.73      0.77       946
    surprise       0.74      0.64      0.69       113

    accuracy                           0.73      3200
   macro avg       0.75      0.68      0.71      3200
weighted avg       0.75      0.73      0.73      3200